version: '3'

services:
  database:
    image: 'mongo:5'
    restart: on-failure
    networks:
      - atp-network
    healthcheck:
      test: ['CMD', 'mongo', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 20s
    ports:
      - '27018:27017'
    volumes:
      - 'mongo-data:/data/db'
    environment:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=P@ssw0rd
      - MONGODB_DATABASE=atp

  backend:
    build:
      context: ./Backend
    restart: always
    networks:
      - atp-network
    ports:
      - '3333:3333'
      - '9229:9229'
    # volumes:
    # - /app/node_modules
    # - ./Backend/:/app/
    depends_on:
      - database
    environment:
      PORT: 3333
      MONGO_URL: 'mongodb://database:27017/atp'
      REACT_APP_URL: 'http://frontend:3000'

    # command: ['npm', 'run', 'dev']
    command: ['npm', 'start']

  frontend:
    build:
      context: ./frontend
    restart: on-failure
    networks:
      - atp-network
    expose:
      - 8080
    ports:
      - '3000:8080'
    environment:
      REACT_APP_BACKEND_URL: 'http://backend:3333'

volumes:
  mongo-data:
    driver: local

networks:
  atp-network:
